"""add is_active field_name to channels

Revision ID: c4f5cec38265
Revises: 122e106d53fa
Create Date: 2025-10-30 23:24:35.539358

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4f5cec38265'
down_revision: Union[str, Sequence[str], None] = '122e106d53fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('channels', sa.Column('is_active', sa.Boolean(), nullable=False, server_default='true'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('channels', 'is_active')
    # ### end Alembic commands ###
